name: my_exam
description: Online UBT test app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

#  basics
  get: ^4.6.5
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.17

#  widgets
  fl_chart: ^0.55.2
  percent_indicator: ^4.2.2
  flutter_spinkit: ^5.1.0
  persistent_bottom_nav_bar: ^5.0.2
  shimmer: ^2.0.0

#  local storage
  shared_preferences: ^2.0.17

  # http
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1

# helpers
  flutter_tex: ^4.0.3+4
  video_player: ^2.6.0
  chewie: ^1.4.0
  tex: ^0.4.3
  tex_text: ^0.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
