name: my_exam
description: Online UBT test app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

#  basics
  get: ^4.6.5
  flutter_svg: ^2.0.6
  google_fonts: ^5.0.0
  flutter_native_splash: ^2.2.17

#  widgets
  fl_chart: ^0.62.0
  percent_indicator: ^4.2.2
  flutter_spinkit: ^5.1.0
  persistent_bottom_nav_bar: ^5.0.2
  shimmer: ^3.0.0

#  local storage
  shared_preferences: ^2.0.17

  # http
  dio: ^5.1.2
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.2

# helpers
  video_player: ^2.6.0
  chewie: ^1.4.0

  flutter_simple_calculator: ^2.2.3
  api_cache_manager: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
